project:
  type: website

website:
  title: "Jap Analysis"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Joberoi23
format:
  html:
    theme: Litera
    css: styles.css



